substitutions:
  _APP_BUCKET_PATH: ''
  _API_BUCKET_PATH: ''
  _NG_BUILD_CONFIG: ''
steps:
- name: node:lts
  entrypoint: npm
  args: ['install']
  env:
    - 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true'

- name: 'gcr.io/cloud-builders/gcloud'
  id: version id for environment files
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/api/src/app/environments/environment.dev.ts
     sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/api/src/app/environments/environment.ts
     sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/meet-app/src/app/environments/environment.dev.ts
     sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/meet-app/src/app/environments/environment.dev.ts

- name: 'gcr.io/$PROJECT_ID/ng:latest'
  args: ['build', '${_NG_BUILD_CONFIG}']

- id: rsync-app-to-storage
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'dist/apps/meet-app', '${_APP_BUCKET_PATH}']

- id: rsync-api-to-storage
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'dist/apps/api', '${_API_BUCKET_PATH}']

- id: never-cache-index
  name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'Cache-Control:no-cache, no-store, max-age=0, must-revalidate'
    - '${_BUCKET_PATH}/index.html'
options:
  machineType: 'N1_HIGHCPU_8'
